### ISSUE TITLE
Add donation button using google play balance

### ISSUE THREAD

**Issue by gturi** [FossifyOrg/Thank-You#20]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Thank-You/issues) or [closed](https://github.com/FossifyOrg/Thank-You/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Thank-You/discussions) or [closed](https://github.com/FossifyOrg/Thank-You/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Thank-You/blob/main/CONTRIBUTING.md).
- [X] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

It would be nice to have a button for donating using google play balance.

### Why do you want this feature?

Sometimes I have spare google play balance I earned through google opinion rewards surveys. It would be nice to have the possibility to use that to support the developers.

**Comment by naveensingh** [comment]
See https://github.com/FossifyOrg/Gallery/discussions/6#discussioncomment-7928256
